Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-21.04"

  config.vm.provider :parallels do |vb|
    vb.name = "__NAME__"
  end

  config.vm.provision "file", source: "~/Developer/dotfiles/git", destination: ".config/git"
  config.vm.provision "file", source: "~/Developer/dotfiles/tmux/tmux.conf", destination: ".config/tmux"
  config.vm.provision "file", source: "~/Developer/dotfiles/tmux/project.tmux", destination: ".local/share/tmux"
  config.vm.provision "file", source: "~/Developer/dotfiles/nvim", destination: ".config/nvim"
  config.vm.provision "file", source: "~/Developer/dotfiles/fish/config.fish", destination: ".config/fish"
  config.vm.provision "file", source: "~/Developer/dotfiles/fish/functions", destination: ".config/fish/functions"

  config.vm.provision "shell", path: "~/Developer/dotfiles/vagrant/ubuntu/setup.sh", privileged: false
end

