Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-21.04"
  config.vm.box_version = "202110.25.0"
  config.vm.hostname = "__NAME__"

  config.vm.provider :parallels do |prl|
    prl.name = "__NAME__"
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "~/Developer/dotfiles/git/config", destination: "~/.config/git/config"
  config.vm.provision "file", source: "~/Developer/dotfiles/fish/config.fish", destination: "~/.config/fish/config.fish"
  config.vm.provision "file", source: "~/Developer/dotfiles/fish/functions", destination: "~/.config/fish/functions"
  config.vm.provision "file", source: "~/Developer/dotfiles/vagrant/ubuntu/update.fish", destination: "~/.config/fish/functions/update.fish"
  config.vm.provision "file", source: "~/Developer/dotfiles/tmux/tmux.conf", destination: "~/.config/tmux/tmux.conf"
  config.vm.provision "file", source: "~/Developer/dotfiles/tmux/project.tmux", destination: "~/.config/tmux/templates/project.tmux"
  config.vm.provision "file", source: "~/Developer/dotfiles/nvim", destination: "~/.config/nvim"

  config.vm.provision "shell", path: "~/Developer/dotfiles/vagrant/ubuntu/setup.sh", privileged: false
end

