Vagrant.configure("2") do |config|
  config.vm.box = "__BOX__"

  config.vm.provider :parallels do |vb|
    vb.name = "__NAME__"
  end

  config.ssh.shell = "zsh -l"

  config.vm.synced_folder ".", "/usr/share/vagrant"

  config.vm.provision "file", source: "~/Developer/dotfiles/git/config", destination: "~/.config/git/config"
  config.vm.provision "file", source: "~/Developer/dotfiles/fish/config.fish", destination: "~/.config/fish/config.fish"
  config.vm.provision "file", source: "~/Developer/dotfiles/fish/functions", destination: "~/.config/fish/functions"
  config.vm.provision "file", source: "~/Developer/dotfiles/tmux/tmux.conf", destination: "~/.config/tmux/tmux.conf"
  config.vm.provision "file", source: "~/Developer/dotfiles/tmux/project.tmux", destination: "~/.config/tmux/templates/project.tmux"
  config.vm.provision "file", source: "~/Developer/dotfiles/nvim", destination: "~/.config/nvim"

  config.vm.provision "shell", path: "~/Developer/dotfiles/vagrant/macos/setup.sh", privileged: false
end
